########### BatchSessionController

### open batch session and send zip parts (required acces token)
POST http://localhost:8082/batch/open-session/1111111111?numberOfParts=11&maxPartSizeMB=0.01
Accept: application/json
Content-Type: application/json

> {%
    const body = response.body;
    const parts = body.split(":");
    const batch_reference_number = parts.length > 1 ? parts[1].trim() : null;

    if (batch_reference_number) {
        client.global.set("sessionReferenceNumber", batch_reference_number);
    } else {
        console.error("ID not found");
    }
%}


### close batch session
POST http://localhost:8082/batch/close-session?referenceNumber={{sessionReferenceNumber}}
Accept: application/json
Content-Type: application/json

######### SessionController
###  check session invoice
GET http://localhost:8082/session/status?referenceNumber={{sessionReferenceNumber}}
Accept: application/json

> {%
    client.global.set("upoReferenceNumber", response.body.upo.pages[0].referenceNumber);
%}

