### get certificate limit

GET http://localhost:8082/limits

Accept: application/json

### certificate enrollment

GET http://localhost:8082/enrollment-info
Accept: application/json

### certificate enrollment process

POST http://localhost:8082/send-enrollment
Accept: application/json
Content-Type: application/json

{
  "commonName": "Kowalski",
  "countryName": "PL",
  "organizationName": "Kowalski sp. z o.o",
  "organizationIdentifier": "VATPL-1111111111"
}

> {%
    client.global.set("certReferenceNumber", response.body.referenceNumber);
%}

### certificate enrollment process status
GET http://localhost:8082/enrollment-status/{{certReferenceNumber}}
Accept: application/json

> {%
    client.global.set("certificateSerialNumber", response.body.certificateSerialNumber);
%}

### certificate metadata list query

POST http://localhost:8082/certListMetadata
Accept: application/json
Content-Type: application/json

{
  "certificateSerialNumber": "{{certificateSerialNumber}}",
  "name" : "",
  "expiresAfter" : ""
}

### certificate list query

POST http://localhost:8082/retrieve
Accept: application/json
Content-Type: application/json

{
  "certificateSerialNumbers": ["{{certificateSerialNumber}}"]
}

### revoke certificate

POST http://localhost:8082/revoke/{{certificateSerialNumber}}
Accept: application/json
Content-Type: application/json


{
  "revocationReason": "Superseded"
}