### grant permissions
POST http://localhost:8082/grant-eu-entity-representative-permissions
Accept: application/json
Content-Type: application/json

{
  "type": "Fingerprint",
  "value": "2222222222"
}

> {%
    client.global.set("referenceNumber", response.body.operationReferenceNumber);
%}

### revoke permissions
POST http://localhost:8082/revoke-eu-entity-representative-permissions
Accept: application/json
Content-Type: application/json

{{referenceNumber}}

> {%
    client.global.set("referenceNumber", response.body.operationReferenceNumber);
%}

###  check permission status
GET http://localhost:8082/{{referenceNumber}}/status
Accept: application/json
