######### ProxyPermissionsEntityController

### Nadanie podmiotom uprawnień do pracy w KSeF
POST http://localhost:8082/grant-proxy-permissions-for-entity
Accept: application/json
Content-Type: application/json

{
    "type": "Nip",
    "value": "2222222222"
}

> {%
    client.global.set("referenceNumber", response.body.operationReferenceNumber);
%}



### Odebranie podmiotom uprawnień do pracy w KSeF
POST http://localhost:8082/revoke-proxy-permissions-for-entity
Accept: application/json
Content-Type: application/json

{{referenceNumber}}

> {%
    client.global.set("referenceNumber", response.body.operationReferenceNumber);
%}

######### IndirectPermissionsEntityController


### Nadanie uprawnień pośrednich do pracy w KSeF
POST http://localhost:8082/grant-indirect-permissions-for-entity
Accept: application/json
Content-Type: application/json

{
  "type": "Nip",
  "value": "2222222222"
}

> {%
    client.global.set("referenceNumber", response.body.operationReferenceNumber);
%}

### Odebranie uprawnień pośrednich do pracy w KSeF
POST http://localhost:8082/revoke-indirect-permissions-for-entity
Accept: application/json
Content-Type: application/json

{{referenceNumber}}

> {%
    client.global.set("referenceNumber", response.body.operationReferenceNumber);
%}


########## OperationStatusController

###  check permission status
GET http://localhost:8082/{{referenceNumber}}/status
Accept: application/json
