### send invoice
POST http://localhost:8082/send-invoice/{{sessionReferenceNumber}}/{{contextIdentifier}}
Accept: application/json
Content-Type: application/json

> {%
    client.global.set("invoiceReferenceNumber", response.body.referenceNumber);
%}



########### SessionController

###  check session invoice
GET http://localhost:8082/session/session-documents?referenceNumber={{sessionReferenceNumber}}
Accept: application/json

> {%
    client.global.set("ksefNumber", response.body.invoices[0].ksefNumber);
    client.global.set("invoiceNumber", response.body.invoices[0].invoiceNumber);
%}


###  download invoice by ksefNumber
GET http://localhost:8082/invoices/ksef/{{ksefNumber}}
Accept: application/json

