### grant personal permissions
POST http://localhost:8082/person-permission/grant-permissions-for-person
Accept: application/json
Content-Type: application/json

{
  "type": "Nip",
  "value": "2222222222"
}

> {%
    client.global.set("referenceNumber", response.body.operationReferenceNumber);
%}

### revoke personal permissions

POST http://localhost:8082/person-permission/revoke-permissions-for-person
Accept: application/json
Content-Type: application/json

{{referenceNumber}}

> {%
    client.global.set("referenceNumber", response.body.operationReferenceNumber);
%}

###  check permission status
GET http://localhost:8082/{{referenceNumber}}/status
Accept: application/json
