### open session
POST http://localhost:8082/open-session
Accept: application/json
Content-Type: application/json

> {%
    client.global.set("sessionReferenceNumber", response.body.referenceNumber);
%}

### session status
GET http://localhost:8082/session/status?referenceNumber={{sessionReferenceNumber}}
Accept: application/json

> {%
    client.global.set("upoReferenceNumber", response.body.upo.pages[0].referenceNumber);
%}

### close session
POST http://localhost:8082/close-session/{{sessionReferenceNumber}}
Accept: application/json
Content-Type: application/json

#--------------------------

### POST /session/query/
POST http://localhost:8080/session/query/10
Content-Type: application/json

{
  "sessionType": "Online",
//  "referenceNumber": "ABC123456",
  "dateCreatedFrom": "2023-01-01T00:00:00Z",
  "dateCreatedTo": "2023-12-31T23:59:59Z",
  "dateClosedFrom": "2023-01-01T00:00:00Z",
  "dateClosedTo": "2023-12-31T23:59:59Z",
  "dateModifiedFrom": "2023-01-01T00:00:00Z",
  "dateModifiedTo": "2023-12-31T23:59:59Z",
  "statuses": ["Succeeded", "InProgress"]
}

### POST /session/active/{pageSize}
POST http://localhost:8082/session/active/10
Content-Type: application/json

### DELETE /session/revoke/current
DELETE http://localhost:8082/session/revoke/current

### DELETE /session/revoke/{sessionReferenceNumber}
DELETE http://localhost:8082/session/revoke/ABC123456
