
### session documents
GET http://localhost:8082/session/session-documents?referenceNumber={{sessionReferenceNumber}}
Accept: application/json

> {%
    client.global.set("ksefNumber", response.body.invoices[0].ksefNumber);
    client.global.set("invoiceNumber", response.body.invoices[0].invoiceNumber);
%}

### invoice upo by ksef number
GET http://localhost:8082/session/invoice-upo?referenceNumber={{sessionReferenceNumber}}&ksefNumber={{ksefNumber}}
Accept: application/xml

### invoice upo by invoice reference number
GET http://localhost:8082/session/invoice-upo?referenceNumber={{sessionReferenceNumber}}&invoiceReferenceNumber={{invoiceNumber}}
Accept: application/xml

### close session
POST http://localhost:8082/close-session/{{sessionReferenceNumber}}
Accept: application/json
Content-Type: application/json

### session status
GET http://localhost:8082/session/status?referenceNumber={{sessionReferenceNumber}}&pageSize=50
Accept: application/json

> {%
    client.global.set("upoReferenceNumber", response.body.upo.pages[0].referenceNumber);
%}

### session upo
GET http://localhost:8082/session/session-upo?referenceNumber={{sessionReferenceNumber}}&upoReferenceNumber={{upoReferenceNumber}}
Accept: application/xml

### failed invoices
GET http://localhost:8082/session/failed-invoices?referenceNumber={{sessionReferenceNumber}}
Accept: application/json

### status invoice
GET http://localhost:8082/session/invoice-status?referenceNumber={{sessionReferenceNumber}}&invoiceReferenceNumber={{invoiceReferenceNumber}}
Accept: application/json