
### Generate KSeF Token
POST http://localhost:8082/generate-token
Content-Type: application/json

> {%
    client.global.set("generateToken", response.body.token);
    client.global.set("generateTokenReferenceNumber", response.body.referenceNumber);
%}
###

### Query KSeF Tokens
POST http://localhost:8082/tokens
Content-Type: application/json

###

### Get KSeF Token by Reference Number
GET http://localhost:8082/token?referenceNumber={{generateTokenReferenceNumber}}
Content-Type: application/json

###

### Revoke KSeF Token
POST http://localhost:8082/revoke-token?referenceNumber={{generateTokenReferenceNumber}}
Content-Type: application/json

###
