//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.akmf.ksef.sdk.client.model.xml;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Challenge">
 *           <simpleType>
 *             <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               <length value="36"/>
 *               <pattern value="\d{8}-CR-[A-F0-9]{10}-[A-F0-9]{10}-[A-F0-9]{2}"/>
 *             </restriction>
 *           </simpleType>
 *         </element>
 *         <element name="ContextIdentifier">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="Type" type="{http://ksef.mf.gov.pl/auth/token/2.0}ContextIdentifierTypeEnum"/>
 *                   <element name="Value" type="{http://ksef.mf.gov.pl/auth/token/2.0}TContextIdentifier"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="SubjectIdentifierType" type="{http://ksef.mf.gov.pl/auth/token/2.0}SubjectIdentifierTypeEnum"/>
 *         <element name="IpAddressPolicy" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="OnClientIpChange" type="{http://ksef.mf.gov.pl/auth/token/2.0}IpChangePolicyEnum" minOccurs="0"/>
 *                   <element name="AllowedIps" minOccurs="0">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence minOccurs="0">
 *                             <element name="IpAddress" maxOccurs="unbounded" minOccurs="0">
 *                               <simpleType>
 *                                 <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   <pattern value="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"/>
 *                                 </restriction>
 *                               </simpleType>
 *                             </element>
 *                             <element name="IpRange" maxOccurs="unbounded" minOccurs="0">
 *                               <simpleType>
 *                                 <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   <pattern value="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}-\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"/>
 *                                 </restriction>
 *                               </simpleType>
 *                             </element>
 *                             <element name="IpMask" maxOccurs="unbounded" minOccurs="0">
 *                               <simpleType>
 *                                 <restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   <pattern value="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/(8|16|24|32)"/>
 *                                 </restriction>
 *                               </simpleType>
 *                             </element>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "challenge",
    "contextIdentifier",
    "subjectIdentifierType",
    "ipAddressPolicy"
})
@XmlRootElement(name = "AuthTokenRequest")
public class AuthTokenRequest {

    @XmlElement(name = "Challenge", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String challenge;
    @XmlElement(name = "ContextIdentifier", required = true)
    protected AuthTokenRequest.ContextIdentifier contextIdentifier;
    @XmlElement(name = "SubjectIdentifierType", required = true)
    @XmlSchemaType(name = "token")
    protected SubjectIdentifierTypeEnum subjectIdentifierType;
    @XmlElement(name = "IpAddressPolicy")
    protected AuthTokenRequest.IpAddressPolicy ipAddressPolicy;

    /**
     * Gets the value of the challenge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChallenge() {
        return challenge;
    }

    /**
     * Sets the value of the challenge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChallenge(String value) {
        this.challenge = value;
    }

    /**
     * Gets the value of the contextIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link AuthTokenRequest.ContextIdentifier }
     *     
     */
    public AuthTokenRequest.ContextIdentifier getContextIdentifier() {
        return contextIdentifier;
    }

    /**
     * Sets the value of the contextIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthTokenRequest.ContextIdentifier }
     *     
     */
    public void setContextIdentifier(AuthTokenRequest.ContextIdentifier value) {
        this.contextIdentifier = value;
    }

    /**
     * Gets the value of the subjectIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectIdentifierTypeEnum }
     *     
     */
    public SubjectIdentifierTypeEnum getSubjectIdentifierType() {
        return subjectIdentifierType;
    }

    /**
     * Sets the value of the subjectIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectIdentifierTypeEnum }
     *     
     */
    public void setSubjectIdentifierType(SubjectIdentifierTypeEnum value) {
        this.subjectIdentifierType = value;
    }

    /**
     * Gets the value of the ipAddressPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link AuthTokenRequest.IpAddressPolicy }
     *     
     */
    public AuthTokenRequest.IpAddressPolicy getIpAddressPolicy() {
        return ipAddressPolicy;
    }

    /**
     * Sets the value of the ipAddressPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthTokenRequest.IpAddressPolicy }
     *     
     */
    public void setIpAddressPolicy(AuthTokenRequest.IpAddressPolicy value) {
        this.ipAddressPolicy = value;
    }

    public AuthTokenRequest withChallenge(String value) {
        setChallenge(value);
        return this;
    }

    public AuthTokenRequest withContextIdentifier(AuthTokenRequest.ContextIdentifier value) {
        setContextIdentifier(value);
        return this;
    }

    public AuthTokenRequest withSubjectIdentifierType(SubjectIdentifierTypeEnum value) {
        setSubjectIdentifierType(value);
        return this;
    }

    public AuthTokenRequest withIpAddressPolicy(AuthTokenRequest.IpAddressPolicy value) {
        setIpAddressPolicy(value);
        return this;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="Type" type="{http://ksef.mf.gov.pl/auth/token/2.0}ContextIdentifierTypeEnum"/>
     *         <element name="Value" type="{http://ksef.mf.gov.pl/auth/token/2.0}TContextIdentifier"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "value"
    })
    public static class ContextIdentifier {

        @XmlElement(name = "Type", required = true)
        @XmlSchemaType(name = "token")
        protected ContextIdentifierTypeEnum type;
        @XmlElement(name = "Value", required = true)
        protected String value;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link ContextIdentifierTypeEnum }
         *     
         */
        public ContextIdentifierTypeEnum getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link ContextIdentifierTypeEnum }
         *     
         */
        public void setType(ContextIdentifierTypeEnum value) {
            this.type = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        public AuthTokenRequest.ContextIdentifier withType(ContextIdentifierTypeEnum value) {
            setType(value);
            return this;
        }

        public AuthTokenRequest.ContextIdentifier withValue(String value) {
            setValue(value);
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="OnClientIpChange" type="{http://ksef.mf.gov.pl/auth/token/2.0}IpChangePolicyEnum" minOccurs="0"/>
     *         <element name="AllowedIps" minOccurs="0">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence minOccurs="0">
     *                   <element name="IpAddress" maxOccurs="unbounded" minOccurs="0">
     *                     <simpleType>
     *                       <restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         <pattern value="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"/>
     *                       </restriction>
     *                     </simpleType>
     *                   </element>
     *                   <element name="IpRange" maxOccurs="unbounded" minOccurs="0">
     *                     <simpleType>
     *                       <restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         <pattern value="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}-\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"/>
     *                       </restriction>
     *                     </simpleType>
     *                   </element>
     *                   <element name="IpMask" maxOccurs="unbounded" minOccurs="0">
     *                     <simpleType>
     *                       <restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         <pattern value="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/(8|16|24|32)"/>
     *                       </restriction>
     *                     </simpleType>
     *                   </element>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "onClientIpChange",
        "allowedIps"
    })
    public static class IpAddressPolicy {

        @XmlElement(name = "OnClientIpChange")
        @XmlSchemaType(name = "string")
        protected IpChangePolicyEnum onClientIpChange;
        @XmlElement(name = "AllowedIps")
        protected AuthTokenRequest.IpAddressPolicy.AllowedIps allowedIps;

        /**
         * Gets the value of the onClientIpChange property.
         * 
         * @return
         *     possible object is
         *     {@link IpChangePolicyEnum }
         *     
         */
        public IpChangePolicyEnum getOnClientIpChange() {
            return onClientIpChange;
        }

        /**
         * Sets the value of the onClientIpChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link IpChangePolicyEnum }
         *     
         */
        public void setOnClientIpChange(IpChangePolicyEnum value) {
            this.onClientIpChange = value;
        }

        /**
         * Gets the value of the allowedIps property.
         * 
         * @return
         *     possible object is
         *     {@link AuthTokenRequest.IpAddressPolicy.AllowedIps }
         *     
         */
        public AuthTokenRequest.IpAddressPolicy.AllowedIps getAllowedIps() {
            return allowedIps;
        }

        /**
         * Sets the value of the allowedIps property.
         * 
         * @param value
         *     allowed object is
         *     {@link AuthTokenRequest.IpAddressPolicy.AllowedIps }
         *     
         */
        public void setAllowedIps(AuthTokenRequest.IpAddressPolicy.AllowedIps value) {
            this.allowedIps = value;
        }

        public AuthTokenRequest.IpAddressPolicy withOnClientIpChange(IpChangePolicyEnum value) {
            setOnClientIpChange(value);
            return this;
        }

        public AuthTokenRequest.IpAddressPolicy withAllowedIps(AuthTokenRequest.IpAddressPolicy.AllowedIps value) {
            setAllowedIps(value);
            return this;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence minOccurs="0">
         *         <element name="IpAddress" maxOccurs="unbounded" minOccurs="0">
         *           <simpleType>
         *             <restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               <pattern value="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"/>
         *             </restriction>
         *           </simpleType>
         *         </element>
         *         <element name="IpRange" maxOccurs="unbounded" minOccurs="0">
         *           <simpleType>
         *             <restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               <pattern value="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}-\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"/>
         *             </restriction>
         *           </simpleType>
         *         </element>
         *         <element name="IpMask" maxOccurs="unbounded" minOccurs="0">
         *           <simpleType>
         *             <restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               <pattern value="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/(8|16|24|32)"/>
         *             </restriction>
         *           </simpleType>
         *         </element>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "ipAddress",
            "ipRange",
            "ipMask"
        })
        public static class AllowedIps {

            @XmlElement(name = "IpAddress")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected List<String> ipAddress;
            @XmlElement(name = "IpRange")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected List<String> ipRange;
            @XmlElement(name = "IpMask")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected List<String> ipMask;

            /**
             * Gets the value of the ipAddress property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the ipAddress property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getIpAddress().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * </p>
             * 
             * 
             * @return
             *     The value of the ipAddress property.
             */
            public List<String> getIpAddress() {
                if (ipAddress == null) {
                    ipAddress = new ArrayList<>();
                }
                return this.ipAddress;
            }

            /**
             * Gets the value of the ipRange property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the ipRange property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getIpRange().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * </p>
             * 
             * 
             * @return
             *     The value of the ipRange property.
             */
            public List<String> getIpRange() {
                if (ipRange == null) {
                    ipRange = new ArrayList<>();
                }
                return this.ipRange;
            }

            /**
             * Gets the value of the ipMask property.
             * 
             * <p>This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the ipMask property.</p>
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * </p>
             * <pre>
             * getIpMask().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * </p>
             * 
             * 
             * @return
             *     The value of the ipMask property.
             */
            public List<String> getIpMask() {
                if (ipMask == null) {
                    ipMask = new ArrayList<>();
                }
                return this.ipMask;
            }

            public AuthTokenRequest.IpAddressPolicy.AllowedIps withIpAddress(String... values) {
                if (values!= null) {
                    for (String value: values) {
                        getIpAddress().add(value);
                    }
                }
                return this;
            }

            public AuthTokenRequest.IpAddressPolicy.AllowedIps withIpAddress(Collection<String> values) {
                if (values!= null) {
                    getIpAddress().addAll(values);
                }
                return this;
            }

            public AuthTokenRequest.IpAddressPolicy.AllowedIps withIpRange(String... values) {
                if (values!= null) {
                    for (String value: values) {
                        getIpRange().add(value);
                    }
                }
                return this;
            }

            public AuthTokenRequest.IpAddressPolicy.AllowedIps withIpRange(Collection<String> values) {
                if (values!= null) {
                    getIpRange().addAll(values);
                }
                return this;
            }

            public AuthTokenRequest.IpAddressPolicy.AllowedIps withIpMask(String... values) {
                if (values!= null) {
                    for (String value: values) {
                        getIpMask().add(value);
                    }
                }
                return this;
            }

            public AuthTokenRequest.IpAddressPolicy.AllowedIps withIpMask(Collection<String> values) {
                if (values!= null) {
                    getIpMask().addAll(values);
                }
                return this;
            }

        }

    }

}
