//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package pl.akmf.ksef.sdk.client.model.xml;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.akmf.ksef.sdk.client.model.xml package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.akmf.ksef.sdk.client.model.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthTokenRequest }
     * 
     * @return
     *     the new instance of {@link AuthTokenRequest }
     */
    public AuthTokenRequest createAuthTokenRequest() {
        return new AuthTokenRequest();
    }

    /**
     * Create an instance of {@link AuthTokenRequest.IpAddressPolicy }
     * 
     * @return
     *     the new instance of {@link AuthTokenRequest.IpAddressPolicy }
     */
    public AuthTokenRequest.IpAddressPolicy createAuthTokenRequestIpAddressPolicy() {
        return new AuthTokenRequest.IpAddressPolicy();
    }

    /**
     * Create an instance of {@link AuthTokenRequest.ContextIdentifier }
     * 
     * @return
     *     the new instance of {@link AuthTokenRequest.ContextIdentifier }
     */
    public AuthTokenRequest.ContextIdentifier createAuthTokenRequestContextIdentifier() {
        return new AuthTokenRequest.ContextIdentifier();
    }

    /**
     * Create an instance of {@link AuthTokenRequest.IpAddressPolicy.AllowedIps }
     * 
     * @return
     *     the new instance of {@link AuthTokenRequest.IpAddressPolicy.AllowedIps }
     */
    public AuthTokenRequest.IpAddressPolicy.AllowedIps createAuthTokenRequestIpAddressPolicyAllowedIps() {
        return new AuthTokenRequest.IpAddressPolicy.AllowedIps();
    }

}
